repos:
  - repo: https://github.com/timothycrosley/isort
    rev: '5.10.1'
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: "22.6.0"
    hooks:
      - id: black
        language_version: python3
